import os
import asyncio
import sys

# Thêm đường dẫn root vào sys.path để import được src.factory
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if project_root not in sys.path:
    sys.path.append(project_root)

from src.factory.config import create_fallback_chain

BATCH_SIZE = 50 # Số dòng mỗi lần dịch
DELAY_SECONDS = 2 # Chờ 2s để tránh rate limit (Mặc dù fallback_chain có sẵn backoff, nhưng vẫn nên sleep chủ động)

async def translate_batch(llm, lines):
    prompt = (
        "Translate the following game dialog lines to Vietnamese.\n"
        "RULES:\n"
        "1. Keep the exact same number of lines.\n"
        "2. Do not add any extra commentary or markdown formatting like ```.\n"
        "3. Preserve any special characters, macros, or variables like {{user}} or \\n.\n\n"
        "TEXT TO TRANSLATE:\n"
    ) + "\n".join(lines)
    
    try:
        response = await llm.ainvoke(prompt)
        
        # Lấy text trả về tùy theo định dạng của object response
        translated_text = response.content.strip() if hasattr(response, 'content') else str(response).strip()
        
        # Remove markdown nếu LLM cứng đầu nhét vào
        if translated_text.startswith("```"):
            translated_text = "\n".join(translated_text.split("\n")[1:-1])
            
        return translated_text.split("\n")
    except Exception as e:
        print(f"Error translating batch: {e}")
        return lines # Trả về text gốc nếu lỗi toàn tập

async def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    input_file = os.path.join(script_dir, "_AutoGeneratedTranslations.txt")
    output_file = os.path.join(script_dir, "_VietnameseTranslations.txt")
    
    if not os.path.exists(input_file):
        print(f"Không tìm thấy file {input_file}!")
        print("Hãy đảm bảo bạn đã đặt file text thô vào cùng thư mục với script này.")
        return

    # Khởi tạo LLM thông qua Fallback Chain của hệ thống (Tự động xài Proxy/API Key của GCLI)
    model_list = ["gemini-2.5-flash", "gemini-1.5-flash", "gemini-3.1-pro-preview"]
    print("Đang khởi tạo LLM Fallback Chain...")
    llm = create_fallback_chain(model_list, temperature=0.1, max_tokens=4096)
    
    with open(input_file, "r", encoding="utf-8") as f:
        content = f.read().splitlines()

    print(f"Tìm thấy {len(content)} dòng cần dịch.")
    
    translated_content = []
    
    for i in range(0, len(content), BATCH_SIZE):
        batch = content[i:i + BATCH_SIZE]
        print(f"Đang dịch mẻ {i//BATCH_SIZE + 1}...")
        
        translated_batch = await translate_batch(llm, batch)
        
        # Đảm bảo số lượng dòng khớp với ban đầu
        if len(translated_batch) != len(batch):
             print(f"Cảnh báo: Lệch số dòng (Gốc: {len(batch)}, Dịch: {len(translated_batch)}).")
             if len(translated_batch) < len(batch):
                 translated_batch.extend(batch[len(translated_batch):])
             else:
                 translated_batch = translated_batch[:len(batch)]
                 
        translated_content.extend(translated_batch)
        await asyncio.sleep(DELAY_SECONDS)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(translated_content))
        
    print(f"Hoàn tất dịch thuật! Kết quả lưu tại: {output_file}")

if __name__ == "__main__":
    asyncio.run(main())
