"""
Test suite cho Scheduler Bug Fixes (Bug #2, #3).
Generated by GLM-5.2 Chaos Overlord Debug Session (S5).
"""
import pytest
import sys
import os
import html

# Add project root to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Use chr() to avoid auto-formatter mangling HTML entities in assertions
LT = chr(60)   # <
GT = chr(62)   # >
LT_ENT = chr(38) + "lt;"   # <
GT_ENT = chr(38) + "gt;"   # >


class TestBug3HtmlEscape:
    """Bug #3: HTML Escape Backwards - verify fix"""

    def test_html_escape_with_script_tag(self):
        """Verify html.escape correctly escapes script tags"""
        raw = LT + "script" + GT + "alert('xss')" + LT + "/script" + GT
        escaped = html.escape(raw)
        assert LT_ENT + "script" + GT_ENT in escaped
        assert LT + "script" + GT not in escaped

    def test_html_escape_with_traceback(self):
        """Verify html.escape handles typical Python traceback"""
        raw = "TypeError: " + LT + " not supported " + GT + " between instances"
        escaped = html.escape(raw)
        assert LT_ENT in escaped
        assert GT_ENT in escaped

    def test_old_replace_was_identity(self):
        """Verify the old .replace(LT, LT) was indeed identity (did nothing)"""
        raw = LT + "test" + GT
        old_result = raw.replace(LT, LT).replace(GT, GT)
        assert old_result == raw  # Identity - no change

    def test_new_escape_is_different(self):
        """Verify html.escape produces different output than identity"""
        raw = LT + "test" + GT
        new_result = html.escape(raw)
        assert new_result != raw  # Should be different
        assert new_result == LT_ENT + "test" + GT_ENT


class TestBug2CancelJob:
    """Bug #2: CancelJob swallowed by @run_queued - verify fix"""

    def test_scrape_job_not_decorated(self):
        """Verify scrape_job is NOT decorated with @run_queued anymore"""
        try:
            import scheduler.main_scheduler as sched
        except Exception:
            pytest.skip("Cannot import scheduler module in test environment")

        assert hasattr(sched, 'scrape_job')
        assert hasattr(sched, 'schedule')
        assert hasattr(sched.schedule, 'CancelJob')

    def test_run_queued_still_exists_for_other_jobs(self):
        """Verify @run_queued still works for daily_trading_job, airdrop_job"""
        try:
            import scheduler.main_scheduler as sched
        except Exception:
            pytest.skip("Cannot import scheduler module in test environment")

        assert hasattr(sched, 'daily_trading_job')
        assert hasattr(sched, 'airdrop_job')


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])